// core/frameworks/catalog.js
const DOMAINS = Object.freeze([
  'strategy',
  'finance',
  'accounting',
  'operations',
  'marketing',
  'technology',
  'organization',
  'people',
  'legal',
]);

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const frameworks = deepFreeze([
  // --- STRATEGY ---
  {
    id: 'mece_principle',
    name: 'MECE Principle',
    domain: 'strategy',
    definition: 'Group information into categories that are mutually exclusive and collectively exhaustive: non-overlapping and complete.',
    whenToUse: 'Any complex problem breakdown or issue-tree construction.',
    expectedOutput: 'A clean, non-redundant issue tree or category set.',
    summary: 'Ensures problem elements are non-overlapping and completely cover the problem space.',
    filePath: 'strategic/mece-principle.md',
  },
  {
    id: 'porters_five_forces',
    name: "Porter's Five Forces",
    domain: 'strategy',
    definition: 'Assess industry structure through rivalry, new entrants, substitutes, buyer power, and supplier power.',
    whenToUse: 'Industry attractiveness, competitive strategy, or market-entry analysis.',
    expectedOutput: 'An attractiveness score with strategic implications.',
    summary: 'Evaluates competitive pressure and industry profitability across 5 structural forces.',
    filePath: 'strategic/porters-five-forces.md',
  },
  {
    id: 'swot_tows',
    name: 'SWOT + TOWS',
    domain: 'strategy',
    definition: 'Compare internal strengths and weaknesses with external opportunities and threats, then convert the diagnosis into actionable TOWS strategies.',
    whenToUse: 'Situational diagnosis or strategy formulation.',
    expectedOutput: 'Prioritized strategic options.',
    summary: 'Pairs internal capabilities with market realities to generate strategic options.',
    filePath: 'strategic/swot-tows.md',
  },
  {
    id: 'mckinsey_7s',
    name: 'McKinsey 7-S',
    domain: 'strategy',
    definition: 'Assess alignment among Strategy, Structure, Systems, Shared Values, Skills, Style, and Staff.',
    whenToUse: 'Organizational diagnosis or change management.',
    expectedOutput: 'Alignment gaps with an intervention plan.',
    summary: 'Evaluates organizational effectiveness by analyzing 7 interconnected internal factors.',
    filePath: 'strategic/mckinsey-7s.md',
  },
  {
    id: 'bcg_growth_share_matrix',
    name: 'BCG Growth-Share Matrix',
    domain: 'strategy',
    definition: 'Classify a portfolio by market growth and relative market share as Stars, Cash Cows, Question Marks, or Dogs.',
    whenToUse: 'Resource allocation across a portfolio.',
    expectedOutput: 'Investment and divestment priorities.',
    summary: 'Categorizes business units to guide strategic capital allocation.',
    filePath: 'strategic/bcg-growth-share-matrix.md',
  },
  {
    id: 'ansoff_matrix',
    name: 'Ansoff Matrix',
    domain: 'strategy',
    definition: 'Evaluate growth through market penetration, market development, product development, and diversification.',
    whenToUse: 'Growth-option evaluation.',
    expectedOutput: 'Ranked growth paths with risk assessment.',
    summary: 'Maps market and product growth vectors against inherent risk.',
    filePath: 'strategic/ansoff-matrix.md',
  },
  {
    id: 'value_chain_analysis',
    name: 'Value Chain Analysis',
    domain: 'strategy',
    definition: 'Examine primary and support activities to identify sources of cost or differentiation advantage.',
    whenToUse: 'Competitive-advantage diagnosis or cost reduction.',
    expectedOutput: 'An activity-level cost and value map.',
    summary: 'Deconstructs internal activities to find margin expansion and differentiation levers.',
    filePath: 'strategic/value-chain-analysis.md',
  },
  {
    id: 'balanced_scorecard_strategy_maps',
    name: 'Balanced Scorecard + Strategy Maps',
    domain: 'strategy',
    definition: 'Connect objectives and metrics across Financial, Customer, Internal Process, and Learning and Growth perspectives.',
    whenToUse: 'Strategy execution or performance management.',
    expectedOutput: 'Cascaded objectives with leading and lagging indicators.',
    summary: 'Translates high-level strategy into operational KPIs across four perspectives.',
    filePath: 'strategic/balanced-scorecard-strategy-maps.md',
  },
  {
    id: 'hypothesis_driven_problem_solving',
    name: 'Hypothesis-Driven Problem Solving / Issue Trees',
    domain: 'strategy',
    definition: 'Start with a hypothesis, structure the problem in MECE form, and test the branches with data.',
    whenToUse: 'Complex problem-solving.',
    expectedOutput: 'A validated or falsified hypothesis supported by evidence.',
    summary: 'Accelerates problem-solving by testing structured early hypotheses.',
    filePath: 'strategic/hypothesis-driven-problem-solving.md',
  },

  // --- FINANCE ---
  {
    id: 'dcf_npv_irr',
    name: 'DCF / NPV / IRR',
    domain: 'finance',
    definition: 'Value an investment using projected free cash flows discounted at WACC or the required return.',
    whenToUse: 'Capital budgeting, mergers and acquisitions, or valuation.',
    expectedOutput: 'NPV, IRR, and sensitivity analysis.',
    summary: 'Evaluates capital investments using discounted cash flows and hurdle rates.',
    filePath: 'finance/dcf-npv-irr.md',
  },
  {
    id: 'dupont_analysis',
    name: 'DuPont Analysis',
    domain: 'finance',
    definition: 'Decompose return on equity into margin, asset turnover, and equity multiplier.',
    whenToUse: 'Performance diagnosis or benchmarking.',
    expectedOutput: 'A driver breakdown of changes in return on equity.',
    summary: 'Decomposes ROE into profitability, asset efficiency, and financial leverage.',
    filePath: 'finance/dupont-analysis.md',
  },
  {
    id: 'working_capital_cash_conversion_cycle',
    name: 'Working Capital / Cash Conversion Cycle',
    domain: 'finance',
    definition: 'Measure operating cash efficiency using CCC = DIO + DSO - DPO.',
    whenToUse: 'Cash-flow optimization or funding growth.',
    expectedOutput: 'A cash-conversion-cycle trend with improvement levers.',
    summary: 'Tracks the time required to convert inventory and resources into cash flows.',
    filePath: 'finance/working-capital-cash-conversion-cycle.md',
  },
  {
    id: 'capital_structure_wacc',
    name: 'Capital Structure & WACC',
    domain: 'finance',
    definition: 'Evaluate the debt and equity mix and its effect on the cost of capital.',
    whenToUse: 'Financing decisions or setting hurdle rates.',
    expectedOutput: 'An optimal capital structure with WACC.',
    summary: 'Calculates the weighted average cost of capital to optimize funding leverage.',
    filePath: 'finance/capital-structure-wacc.md',
  },
  {
    id: 'unit_economics_contribution_margin',
    name: 'Unit Economics & Contribution Margin',
    domain: 'finance',
    definition: 'Assess revenue less variable costs together with customer acquisition cost and customer lifetime value.',
    whenToUse: 'Pricing, product-mix decisions, or growth-viability analysis.',
    expectedOutput: 'Break-even, payback, and scalability assessment.',
    summary: 'Analyzes unit-level profitability, LTV, and CAC payback dynamics.',
    filePath: 'finance/unit-economics-contribution-margin.md',
  },

  // --- ACCOUNTING ---
  {
    id: 'three_financial_statements_integration',
    name: 'Three Financial Statements Integration',
    domain: 'accounting',
    definition: 'Link the income statement, balance sheet, and cash-flow statement and explain how changes flow among them.',
    whenToUse: 'Any financial analysis or forecast.',
    expectedOutput: 'Linked statements with quality-of-earnings insight.',
    summary: 'Dynamically links Income Statement, Balance Sheet, and Cash Flow Statement.',
    filePath: 'accounting/three-financial-statements-integration.md',
  },
  {
    id: 'ratio_analysis',
    name: 'Ratio Analysis',
    domain: 'accounting',
    definition: 'Analyze liquidity, profitability, efficiency, leverage, and coverage ratios.',
    whenToUse: 'Performance monitoring or benchmarking.',
    expectedOutput: 'A ratio dashboard with trends and red flags.',
    summary: 'Evaluates financial health across liquidity, leverage, and margin metrics.',
    filePath: 'accounting/ratio-analysis.md',
  },
  {
    id: 'activity_based_costing',
    name: 'Activity-Based Costing',
    domain: 'accounting',
    definition: 'Allocate overhead according to the activities and cost drivers that actually consume resources.',
    whenToUse: 'Accurate product or service costing.',
    expectedOutput: 'True cost and margin by activity.',
    summary: 'Assigns indirect costs directly to resource-consuming activities.',
    filePath: 'accounting/activity-based-costing.md',
  },
  {
    id: 'break_even_contribution_margin_analysis',
    name: 'Break-Even & Contribution Margin Analysis',
    domain: 'accounting',
    definition: 'Determine the volume at which total contribution margin equals fixed costs.',
    whenToUse: 'Pricing or volume decisions.',
    expectedOutput: 'A break-even point with sensitivity analysis.',
    summary: 'Calculates the exact revenue volume required to cover fixed overhead.',
    filePath: 'accounting/break-even-contribution-margin-analysis.md',
  },

  // --- OPERATIONS ---
  {
    id: 'lean_toyota_production_system',
    name: 'Lean / Toyota Production System',
    domain: 'operations',
    definition: 'Improve flow by eliminating waste through kaizen, just-in-time practices, and pull systems.',
    whenToUse: 'Process efficiency or lead-time reduction.',
    expectedOutput: 'A value-stream map with waste-reduction actions.',
    summary: 'Identifies and eliminates non-value-add operational waste (Muda).',
    filePath: 'operations/lean-toyota-production-system.md',
  },
  {
    id: 'six_sigma_dmaic',
    name: 'Six Sigma / DMAIC',
    domain: 'operations',
    definition: 'Reduce process variation through Define, Measure, Analyze, Improve, and Control.',
    whenToUse: 'Process-variation reduction.',
    expectedOutput: 'Statistical process control with improved capability.',
    summary: 'Reduces defects and process variance through structured statistical steps.',
    filePath: 'operations/six-sigma-dmaic.md',
  },
  {
    id: 'theory_of_constraints',
    name: 'Theory of Constraints',
    domain: 'operations',
    definition: "Identify the system's bottleneck and subordinate, exploit, and elevate it to increase throughput.",
    whenToUse: 'Throughput maximization.',
    expectedOutput: 'Constraint identification with an elevation plan.',
    summary: 'Focuses operational improvements exclusively on the primary system bottleneck.',
    filePath: 'operations/theory-of-constraints.md',
  },
  {
    id: 'scor_model',
    name: 'SCOR Model',
    domain: 'operations',
    definition: 'Assess supply-chain performance through Plan, Source, Make, Deliver, and Return.',
    whenToUse: 'Supply-chain design or performance improvement.',
    expectedOutput: 'Process metrics with an improvement roadmap.',
    summary: 'Standardizes supply chain performance across Plan, Source, Make, Deliver, and Return.',
    filePath: 'operations/scor-model.md',
  },
  {
    id: 'capacity_planning_throughput_analysis',
    name: 'Capacity Planning & Throughput Analysis',
    domain: 'operations',
    definition: 'Match available capacity and throughput to current and forecast demand.',
    whenToUse: 'Scaling or bottleneck relief.',
    expectedOutput: 'A capacity model with a utilization plan.',
    summary: 'Aligns infrastructure and labor limits with forecasted volume.',
    filePath: 'operations/capacity-planning-throughput-analysis.md',
  },

  // --- MARKETING ---
  {
    id: 'stp_framework',
    name: 'STP Framework',
    domain: 'marketing',
    definition: 'Develop market strategy through Segmentation, Targeting, and Positioning.',
    whenToUse: 'Market strategy or go-to-market planning.',
    expectedOutput: 'Chosen segments with a positioning statement.',
    summary: 'Segments the audience, selects targets, and defines market positioning.',
    filePath: 'marketing/stp-framework.md',
  },
  {
    id: 'marketing_mix_4ps_7ps',
    name: '4Ps / 7Ps Marketing Mix',
    domain: 'marketing',
    definition: 'Coordinate Product, Price, Place, and Promotion, plus People, Process, and Physical Evidence where relevant.',
    whenToUse: 'Tactical marketing planning.',
    expectedOutput: 'A coherent marketing mix.',
    summary: 'Coordinates execution tactics across Product, Price, Place, and Promotion.',
    filePath: 'marketing/marketing-mix-4ps-7ps.md',
  },
  {
    id: 'jobs_to_be_done',
    name: 'Jobs-to-be-Done',
    domain: 'marketing',
    definition: 'Describe the progress customers seek when they hire a product or service.',
    whenToUse: 'Innovation or positioning.',
    expectedOutput: 'Job statements with solution criteria.',
    summary: 'Focuses product positioning on the fundamental task the buyer is hiring it for.',
    filePath: 'marketing/jobs-to-be-done.md',
  },
  {
    id: 'clv_cac',
    name: 'CLV + CAC',
    domain: 'marketing',
    definition: 'Compare customer lifetime value with customer acquisition cost.',
    whenToUse: 'Growth economics or retention investment.',
    expectedOutput: 'A CLV:CAC ratio with payback period.',
    summary: 'Evaluates growth sustainability by contrasting acquisition cost with total lifetime value.',
    filePath: 'marketing/clv-cac.md',
  },
  {
    id: 'aarrr_pirate_metrics',
    name: 'AARRR (Pirate Metrics)',
    domain: 'marketing',
    definition: 'Measure Acquisition, Activation, Retention, Revenue, and Referral.',
    whenToUse: 'Digital or growth optimization.',
    expectedOutput: 'Funnel diagnostics.',
    summary: 'Tracks the growth engine across Acquisition, Activation, Retention, Revenue, and Referral.',
    filePath: 'marketing/aarrr-pirate-metrics.md',
  },
  {
    id: 'customer_journey_mapping',
    name: 'Customer Journey Mapping',
    domain: 'marketing',
    definition: 'Visualize the end-to-end customer experience across interactions and stages.',
    whenToUse: 'Experience design.',
    expectedOutput: 'A journey map with prioritized friction points.',
    summary: 'Maps user touchpoints and emotional friction from awareness to advocacy.',
    filePath: 'marketing/customer-journey-mapping.md',
  },

  // --- TECHNOLOGY ---
  {
    id: 'dora_metrics',
    name: 'DORA Metrics',
    domain: 'technology',
    definition: 'Assess software delivery through Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.',
    whenToUse: 'Software delivery performance assessment.',
    expectedOutput: 'A four-metric delivery health snapshot.',
    summary: 'Measures DevOps performance via speed and stability metrics.',
    filePath: 'technology/dora-metrics.md',
  },
  {
    id: 'space_framework',
    name: 'SPACE Framework',
    domain: 'technology',
    definition: 'Assess developer productivity across Satisfaction, Performance, Activity, Communication and Collaboration, and Efficiency and Flow.',
    whenToUse: 'Broader developer productivity assessment beyond activity metrics.',
    expectedOutput: 'A multi-dimension productivity view.',
    summary: 'Evaluates developer productivity comprehensively across 5 dimensions.',
    filePath: 'technology/space-framework.md',
  },
  {
    id: 'architecture_decision_records',
    name: 'Architecture Decision Records (ADRs)',
    domain: 'technology',
    definition: 'Capture the context, decision, and consequences of significant technical choices in lightweight records.',
    whenToUse: 'Any irreversible or high-impact technical decision.',
    expectedOutput: 'A context, decision, and consequences record.',
    summary: 'Documents high-impact technical decisions, options, and tradeoffs.',
    filePath: 'technology/architecture-decision-records.md',
  },
  {
    id: 'c4_model',
    name: 'C4 Model',
    domain: 'technology',
    definition: 'Describe software architecture hierarchically through Context, Containers, Components, and Code.',
    whenToUse: 'Communicating system architecture at the right level of abstraction.',
    expectedOutput: 'Layered architecture views.',
    summary: 'Visualizes software design through Context, Containers, Components, and Code.',
    filePath: 'technology/c4-model.md',
  },
  {
    id: 'wardley_mapping',
    name: 'Wardley Mapping',
    domain: 'technology',
    definition: 'Map value-chain components against evolution stages of genesis, custom, product, and commodity to guide sourcing choices.',
    whenToUse: 'Technology strategy and sourcing decisions.',
    expectedOutput: 'A positioned value-chain map with strategic implications.',
    summary: 'Maps system dependencies against technological maturity stages.',
    filePath: 'technology/wardley-mapping.md',
  },
  {
    id: 'domain_driven_design_strategic_patterns',
    name: 'Domain-Driven Design (strategic patterns)',
    domain: 'technology',
    definition: 'Decompose complex domains using bounded contexts, ubiquitous language, and context mapping.',
    whenToUse: 'Complex domain modeling or system decomposition.',
    expectedOutput: 'A bounded-context map.',
    summary: 'Decomposes complex systems into isolated, bounded domain contexts.',
    filePath: 'technology/domain-driven-design-strategic-patterns.md',
  },
  {
    id: 'technology_radar',
    name: 'Technology Radar',
    domain: 'technology',
    definition: 'Govern technology choices by categorizing tools and techniques as Adopt, Trial, Assess, or Hold.',
    whenToUse: 'Technology-choice governance.',
    expectedOutput: 'A categorized adoption recommendation.',
    summary: 'Tracks and governs tool choices across Adopt, Trial, Assess, and Hold rings.',
    filePath: 'technology/technology-radar.md',
  },
  {
    id: 'build_buy_partner',
    name: 'Build vs Buy vs Partner',
    domain: 'technology',
    definition: 'Compare sourcing options using total cost of ownership, differentiation, and risk.',
    whenToUse: 'Sourcing decisions.',
    expectedOutput: 'A recommended sourcing path with rationale.',
    summary: 'Evaluates software acquisition choices using core capability and TCO factors.',
    filePath: 'technology/build-buy-partner.md',
  },
  {
    id: 'sre_principles',
    name: 'SRE Principles',
    domain: 'technology',
    definition: 'Guide reliability through error budgets, service-level objectives and indicators, toil reduction, and blameless postmortems.',
    whenToUse: 'Reliability decisions and incident-response posture.',
    expectedOutput: 'A reliability target with operating discipline.',
    summary: 'Governs system uptime using SLOs, error budgets, and toil elimination.',
    filePath: 'technology/sre-principles.md',
  },
  {
    id: 'threat_modeling',
    name: 'Threat Modeling (STRIDE or equivalent)',
    domain: 'technology',
    definition: 'Identify security risks systematically using STRIDE or an equivalent threat categorization method.',
    whenToUse: 'Security-relevant technical decisions.',
    expectedOutput: 'Identified threat categories with mitigations.',
    summary: 'Systematically uncovers security vulnerabilities using the STRIDE framework.',
    filePath: 'technology/threat-modeling.md',
  },

  // --- ORGANIZATION ---
  {
    id: 'okrs',
    name: 'OKRs',
    domain: 'organization',
    definition: 'Set qualitative Objectives supported by measurable Key Results.',
    whenToUse: 'Goal setting or execution cadence.',
    expectedOutput: 'A cascaded OKR set with tracking.',
    summary: 'Aligns company and department goals via Objectives and Key Results.',
    filePath: 'organization/okrs.md',
  },
  {
    id: 'raci_matrix',
    name: 'RACI Matrix',
    domain: 'organization',
    definition: 'Clarify decision and delivery roles as Responsible, Accountable, Consulted, and Informed.',
    whenToUse: 'Project governance or decision-rights clarity.',
    expectedOutput: 'A RACI chart.',
    summary: 'Maps stakeholder responsibility: Responsible, Accountable, Consulted, Informed.',
    filePath: 'organization/raci-matrix.md',
  },
  {
    id: 'scenario_planning_decision_trees_expected_value',
    name: 'Scenario Planning & Decision Trees / Expected Value',
    domain: 'organization',
    definition: 'Structure alternative futures and compare decision paths using probabilities, outcomes, and expected value.',
    whenToUse: 'High-uncertainty decisions.',
    expectedOutput: 'A preferred option across scenarios with expected value.',
    summary: 'Models uncertain outcomes with probabilistic branches and expected value.',
    filePath: 'organization/scenario-planning-decision-trees-expected-value.md',
  },
  {
    id: 'pyramid_principle',
    name: 'Pyramid Principle',
    domain: 'organization',
    definition: 'Lead with the governing thought, followed by MECE-grouped supporting arguments.',
    whenToUse: 'All executive communication.',
    expectedOutput: 'A clear top-down recommendation structure.',
    summary: 'Structures executive communications answer-first with MECE logic.',
    filePath: 'organization/pyramid-principle.md',
  },
  {
    id: 'bezos_type_1_type_2_decisions',
    name: 'Bezos Type 1 / Type 2 Decisions',
    domain: 'organization',
    definition: 'Classify irreversible, high-cost decisions as Type 1 and reversible, low-cost decisions as Type 2.',
    whenToUse: 'Any decision requiring an escalate-or-act determination.',
    expectedOutput: 'A decision classification with recommended decision speed.',
    summary: 'Categorizes decisions by reversibility to optimize execution speed.',
    filePath: 'organization/bezos-type-1-type-2-decisions.md',
  },

  // --- PEOPLE ---
  {
    id: 'galbraiths_star_model',
    name: "Galbraith's Star Model",
    domain: 'people',
    definition: 'Align five organizational design levers — Strategy, Structure, Processes, Rewards, and People — so that each reinforces the others rather than working against them.',
    whenToUse: 'Organization design, restructuring, or diagnosing why structure and incentives pull against strategy.',
    expectedOutput: 'A five-lever alignment diagnosis identifying which design levers to change.',
    summary: 'Aligns 5 levers: Strategy, Structure, Processes, Rewards, and People.',
    filePath: 'people/galbraiths-star-model.md',
  },
  {
    id: 'spans_and_layers',
    name: 'Spans and Layers',
    domain: 'people',
    definition: 'Analyze managerial spans of control and the number of reporting layers between the top and the front line.',
    whenToUse: 'Diagnosing organizational drag, management cost, or slow decision flow.',
    expectedOutput: 'A spans-and-layers profile with delayering or re-span recommendations.',
    summary: 'Audits management reporting depth and direct-report density.',
    filePath: 'people/spans-and-layers.md',
  },
  {
    id: 'nine_box_grid',
    name: '9-Box Grid',
    domain: 'people',
    definition: 'Assess talent on a grid of demonstrated performance against assessed potential to inform development and succession reasoning.',
    whenToUse: 'Talent review, succession planning, or development prioritization.',
    expectedOutput: 'A placement rationale with development or succession actions per segment.',
    summary: 'Maps employee talent on a performance-versus-potential grid.',
    filePath: 'people/nine-box-grid.md',
  },
  {
    id: 'skill_will_matrix',
    name: 'Skill-Will Matrix',
    domain: 'people',
    definition: "Match a person's skill and will for a specific task to the right leadership response — direct, guide, excite, or delegate.",
    whenToUse: 'Choosing a delegation or coaching approach, or diagnosing task-level performance.',
    expectedOutput: 'A quadrant placement with the matched management response.',
    summary: 'Matches leadership delegation style (Direct, Guide, Excite, Delegate) to team readiness.',
    filePath: 'people/skill-will-matrix.md',
  },
  {
    id: 'employee_experience_equation',
    name: 'Employee Experience (EX) Equation',
    domain: 'people',
    definition: 'Frame employee experience as the gap between employee expectations and the reality the organization delivers across the work, the people, and the environment.',
    whenToUse: 'Diagnosing engagement, attrition, or experience gaps.',
    expectedOutput: 'An expectation-versus-reality gap analysis with prioritized interventions.',
    summary: 'Measures engagement friction across expectations versus operational delivery.',
    filePath: 'people/employee-experience-equation.md',
  },
  {
    id: 'competing_values_framework',
    name: 'Competing Values Framework',
    domain: 'people',
    definition: 'Diagnose organizational culture across four quadrants — Clan, Adhocracy, Market, and Hierarchy — defined by internal-versus-external focus and flexibility-versus-control.',
    whenToUse: 'Culture diagnosis, culture change, or leadership-style alignment.',
    expectedOutput: 'A current-versus-target culture profile with the shift required.',
    summary: 'Diagnoses company culture across Clan, Adhocracy, Market, and Hierarchy.',
    filePath: 'people/competing-values-framework.md',
  },
  {
    id: 'scarf_model',
    name: 'SCARF Model',
    domain: 'people',
    definition: 'Assess how a change affects Status, Certainty, Autonomy, Relatedness, and Fairness — the social domains that drive threat or reward responses.',
    whenToUse: 'Change communication, feedback, or any people-affecting decision that could trigger a threat response.',
    expectedOutput: 'A per-domain risk read with mitigations for the social response.',
    summary: 'Predicts change resistance across Status, Certainty, Autonomy, Relatedness, and Fairness.',
    filePath: 'people/scarf-model.md',
  },
  {
    id: 'kotters_8_step',
    name: "Kotter's 8-Step Change Model",
    domain: 'people',
    definition: 'Lead large-scale change through eight steps, from establishing urgency to anchoring new approaches in the culture.',
    whenToUse: 'Planning and sequencing a major organizational change.',
    expectedOutput: 'A staged change plan identifying the current step and next actions.',
    summary: 'Sequences organizational transformation through eight structured phases.',
    filePath: 'people/kotters-8-step.md',
  },
  {
    id: 'adkar_model',
    name: 'ADKAR Model',
    domain: 'people',
    definition: 'Diagnose individual change readiness across Awareness, Desire, Knowledge, Ability, and Reinforcement.',
    whenToUse: 'Diagnosing where an individual or group is stuck in adopting a change.',
    expectedOutput: 'The blocking ADKAR stage with the targeted intervention.',
    summary: 'Tracks individual adoption through Awareness, Desire, Knowledge, Ability, and Reinforcement.',
    filePath: 'people/adkar-model.md',
  },
  {
    id: 'worldatwork_total_rewards',
    name: 'WorldatWork Total Rewards',
    domain: 'people',
    definition: 'Frame the full employment value exchange across compensation, benefits, well-being, recognition, and development, rather than base pay alone.',
    whenToUse: 'Designing or explaining a rewards approach, or diagnosing a retention or offer problem.',
    expectedOutput: 'A total-rewards view identifying the levers beyond base pay.',
    summary: 'Evaluates employee compensation beyond base pay across 5 holistic pillars.',
    filePath: 'people/worldatwork-total-rewards.md',
  },
  {
    id: 'lamp_framework',
    name: 'LAMP Framework',
    domain: 'people',
    definition: 'Connect talent decisions to strategic impact through Logic, Analytics, Measures, and Process, so people metrics change real decisions rather than only reporting activity.',
    whenToUse: 'Deciding which people metrics matter and how they should drive a specific decision.',
    expectedOutput: 'A decision-linked measurement plan rather than an activity dashboard.',
    summary: 'Connects workforce metrics to business strategy via Logic, Analytics, Measures, Process.',
    filePath: 'people/lamp-framework.md',
  },

  // --- LEGAL ---
  {
    id: 'irac_legal_analysis',
    name: 'IRAC Legal Analysis',
    domain: 'legal',
    definition: 'Analyze a legal question through Issue, Rule, Application, and Conclusion, separating the governing rule from its application to the specific facts.',
    whenToUse: 'Structured legal issue spotting or a reasoned position on a specific question.',
    expectedOutput: 'A labeled issue, rule, application, and conclusion with the qualified-counsel dependency named.',
    summary: 'Structures legal reasoning into Issue, Rule, Application, and Conclusion.',
    filePath: 'legal/irac-legal-analysis.md',
  },
  {
    id: 'regulatory_compliance_mapping',
    name: 'Regulatory Compliance Mapping',
    domain: 'legal',
    definition: 'Map applicable laws and regulations to concrete obligations, the controls that satisfy them, and the owner accountable for each.',
    whenToUse: 'Assessing regulatory exposure or building a compliance obligation register.',
    expectedOutput: 'An obligation-to-control-to-owner map with identified gaps.',
    summary: 'Connects legal mandates directly to internal business controls and owners.',
    filePath: 'legal/regulatory-compliance-mapping.md',
  },
  {
    id: 'contract_risk_allocation',
    name: 'Contract Risk Allocation',
    domain: 'legal',
    definition: 'Allocate risk between parties through indemnification, limitation of liability, warranties, termination, and intellectual-property terms.',
    whenToUse: 'Reviewing or structuring an agreement before qualified-counsel sign-off.',
    expectedOutput: 'A clause-level risk-allocation summary with flagged exposures and escalation points.',
    summary: 'Audits agreement terms for indemnification, liability caps, and exposure risks.',
    filePath: 'legal/contract-risk-allocation.md',
  },
  {
    id: 'enterprise_risk_management',
    name: 'Enterprise Risk Management (COSO / Three Lines of Defense)',
    domain: 'legal',
    definition: 'Identify, assess, own, and govern enterprise risk across the operating, oversight, and assurance lines of defense.',
    whenToUse: 'Governance-level risk assessment or assigning risk ownership across the organization.',
    expectedOutput: 'A prioritized risk register with owners and defense-line accountability.',
    summary: 'Governs organization risk via COSO principles and the Three Lines of Defense model.',
    filePath: 'legal/enterprise-risk-management.md',
  },
  {
    id: 'legal_hold_and_privilege',
    name: 'Legal Hold & Privilege Preservation',
    domain: 'legal',
    definition: 'Preserve attorney-client privilege and issue and enforce legal holds when litigation, a dispute, or an investigation is reasonably anticipated.',
    whenToUse: 'Anticipated litigation, a dispute, or a regulatory investigation.',
    expectedOutput: 'A hold scope, custodian list, and privilege-preservation posture with counsel escalation.',
    summary: 'Establishes document preservation and legal privilege routines during disputes.',
    filePath: 'legal/legal-hold-and-privilege.md',
  },
  {
    id: 'regulatory_horizon_scanning',
    name: 'Regulatory Horizon Scanning',
    domain: 'legal',
    definition: 'Systematically track upcoming legal and regulatory change and assess its impact on current obligations and commitments.',
    whenToUse: 'Anticipating regulatory change or assessing forward compliance exposure.',
    expectedOutput: 'A watchlist of pending changes with assessed impact and recommended preparation.',
    summary: 'Monitors upcoming legislative changes to proactively adapt business compliance.',
    filePath: 'legal/regulatory-horizon-scanning.md',
  },
]);

function getAllFrameworks() {
  return frameworks;
}

function getFrameworksByDomain(domain) {
  return frameworks.filter(framework => framework.domain === String(domain || '').trim().toLowerCase());
}

function getFrameworkById(id) {
  return frameworks.find(framework => framework.id === String(id || '').trim().toLowerCase()) || null;
}

module.exports = {
  DOMAINS,
  frameworks,
  getAllFrameworks,
  getFrameworksByDomain,
  getFrameworkById,
};