const DOMAINS = Object.freeze([
  'strategy',
  'finance',
  'accounting',
  'operations',
  'marketing',
  'organization',
]);

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const frameworks = deepFreeze([
  {
    id: 'mece_principle',
    name: 'MECE Principle',
    domain: 'strategy',
    definition: 'Group information into categories that are mutually exclusive and collectively exhaustive: non-overlapping and complete.',
    whenToUse: 'Any complex problem breakdown or issue-tree construction.',
    expectedOutput: 'A clean, non-redundant issue tree or category set.',
  },
  {
    id: 'porters_five_forces',
    name: "Porter's Five Forces",
    domain: 'strategy',
    definition: 'Assess industry structure through rivalry, new entrants, substitutes, buyer power, and supplier power.',
    whenToUse: 'Industry attractiveness, competitive strategy, or market-entry analysis.',
    expectedOutput: 'An attractiveness score with strategic implications.',
  },
  {
    id: 'swot_tows',
    name: 'SWOT + TOWS',
    domain: 'strategy',
    definition: 'Compare internal strengths and weaknesses with external opportunities and threats, then convert the diagnosis into actionable TOWS strategies.',
    whenToUse: 'Situational diagnosis or strategy formulation.',
    expectedOutput: 'Prioritized strategic options.',
  },
  {
    id: 'mckinsey_7s',
    name: 'McKinsey 7-S',
    domain: 'strategy',
    definition: 'Assess alignment among Strategy, Structure, Systems, Shared Values, Skills, Style, and Staff.',
    whenToUse: 'Organizational diagnosis or change management.',
    expectedOutput: 'Alignment gaps with an intervention plan.',
  },
  {
    id: 'bcg_growth_share_matrix',
    name: 'BCG Growth-Share Matrix',
    domain: 'strategy',
    definition: 'Classify a portfolio by market growth and relative market share as Stars, Cash Cows, Question Marks, or Dogs.',
    whenToUse: 'Resource allocation across a portfolio.',
    expectedOutput: 'Investment and divestment priorities.',
  },
  {
    id: 'ansoff_matrix',
    name: 'Ansoff Matrix',
    domain: 'strategy',
    definition: 'Evaluate growth through market penetration, market development, product development, and diversification.',
    whenToUse: 'Growth-option evaluation.',
    expectedOutput: 'Ranked growth paths with risk assessment.',
  },
  {
    id: 'value_chain_analysis',
    name: 'Value Chain Analysis',
    domain: 'strategy',
    definition: 'Examine primary and support activities to identify sources of cost or differentiation advantage.',
    whenToUse: 'Competitive-advantage diagnosis or cost reduction.',
    expectedOutput: 'An activity-level cost and value map.',
  },
  {
    id: 'balanced_scorecard_strategy_maps',
    name: 'Balanced Scorecard + Strategy Maps',
    domain: 'strategy',
    definition: 'Connect objectives and metrics across Financial, Customer, Internal Process, and Learning and Growth perspectives.',
    whenToUse: 'Strategy execution or performance management.',
    expectedOutput: 'Cascaded objectives with leading and lagging indicators.',
  },
  {
    id: 'hypothesis_driven_problem_solving',
    name: 'Hypothesis-Driven Problem Solving / Issue Trees',
    domain: 'strategy',
    definition: 'Start with a hypothesis, structure the problem in MECE form, and test the branches with data.',
    whenToUse: 'Complex problem-solving.',
    expectedOutput: 'A validated or falsified hypothesis supported by evidence.',
  },
  {
    id: 'dcf_npv_irr',
    name: 'DCF / NPV / IRR',
    domain: 'finance',
    definition: 'Value an investment using projected free cash flows discounted at WACC or the required return.',
    whenToUse: 'Capital budgeting, mergers and acquisitions, or valuation.',
    expectedOutput: 'NPV, IRR, and sensitivity analysis.',
  },
  {
    id: 'dupont_analysis',
    name: 'DuPont Analysis',
    domain: 'finance',
    definition: 'Decompose return on equity into margin, asset turnover, and equity multiplier.',
    whenToUse: 'Performance diagnosis or benchmarking.',
    expectedOutput: 'A driver breakdown of changes in return on equity.',
  },
  {
    id: 'working_capital_cash_conversion_cycle',
    name: 'Working Capital / Cash Conversion Cycle',
    domain: 'finance',
    definition: 'Measure operating cash efficiency using CCC = DIO + DSO - DPO.',
    whenToUse: 'Cash-flow optimization or funding growth.',
    expectedOutput: 'A cash-conversion-cycle trend with improvement levers.',
  },
  {
    id: 'capital_structure_wacc',
    name: 'Capital Structure & WACC',
    domain: 'finance',
    definition: 'Evaluate the debt and equity mix and its effect on the cost of capital.',
    whenToUse: 'Financing decisions or setting hurdle rates.',
    expectedOutput: 'An optimal capital structure with WACC.',
  },
  {
    id: 'unit_economics_contribution_margin',
    name: 'Unit Economics & Contribution Margin',
    domain: 'finance',
    definition: 'Assess revenue less variable costs together with customer acquisition cost and customer lifetime value.',
    whenToUse: 'Pricing, product-mix decisions, or growth-viability analysis.',
    expectedOutput: 'Break-even, payback, and scalability assessment.',
  },
  {
    id: 'three_financial_statements_integration',
    name: 'Three Financial Statements Integration',
    domain: 'accounting',
    definition: 'Link the income statement, balance sheet, and cash-flow statement and explain how changes flow among them.',
    whenToUse: 'Any financial analysis or forecast.',
    expectedOutput: 'Linked statements with quality-of-earnings insight.',
  },
  {
    id: 'ratio_analysis',
    name: 'Ratio Analysis',
    domain: 'accounting',
    definition: 'Analyze liquidity, profitability, efficiency, leverage, and coverage ratios.',
    whenToUse: 'Performance monitoring or benchmarking.',
    expectedOutput: 'A ratio dashboard with trends and red flags.',
  },
  {
    id: 'activity_based_costing',
    name: 'Activity-Based Costing',
    domain: 'accounting',
    definition: 'Allocate overhead according to the activities and cost drivers that actually consume resources.',
    whenToUse: 'Accurate product or service costing.',
    expectedOutput: 'True cost and margin by activity.',
  },
  {
    id: 'break_even_contribution_margin_analysis',
    name: 'Break-Even & Contribution Margin Analysis',
    domain: 'accounting',
    definition: 'Determine the volume at which total contribution margin equals fixed costs.',
    whenToUse: 'Pricing or volume decisions.',
    expectedOutput: 'A break-even point with sensitivity analysis.',
  },
  {
    id: 'lean_toyota_production_system',
    name: 'Lean / Toyota Production System',
    domain: 'operations',
    definition: 'Improve flow by eliminating waste through kaizen, just-in-time practices, and pull systems.',
    whenToUse: 'Process efficiency or lead-time reduction.',
    expectedOutput: 'A value-stream map with waste-reduction actions.',
  },
  {
    id: 'six_sigma_dmaic',
    name: 'Six Sigma / DMAIC',
    domain: 'operations',
    definition: 'Reduce process variation through Define, Measure, Analyze, Improve, and Control.',
    whenToUse: 'Process-variation reduction.',
    expectedOutput: 'Statistical process control with improved capability.',
  },
  {
    id: 'theory_of_constraints',
    name: 'Theory of Constraints',
    domain: 'operations',
    definition: "Identify the system's bottleneck and subordinate, exploit, and elevate it to increase throughput.",
    whenToUse: 'Throughput maximization.',
    expectedOutput: 'Constraint identification with an elevation plan.',
  },
  {
    id: 'scor_model',
    name: 'SCOR Model',
    domain: 'operations',
    definition: 'Assess supply-chain performance through Plan, Source, Make, Deliver, and Return.',
    whenToUse: 'Supply-chain design or performance improvement.',
    expectedOutput: 'Process metrics with an improvement roadmap.',
  },
  {
    id: 'capacity_planning_throughput_analysis',
    name: 'Capacity Planning & Throughput Analysis',
    domain: 'operations',
    definition: 'Match available capacity and throughput to current and forecast demand.',
    whenToUse: 'Scaling or bottleneck relief.',
    expectedOutput: 'A capacity model with a utilization plan.',
  },
  {
    id: 'stp_framework',
    name: 'STP Framework',
    domain: 'marketing',
    definition: 'Develop market strategy through Segmentation, Targeting, and Positioning.',
    whenToUse: 'Market strategy or go-to-market planning.',
    expectedOutput: 'Chosen segments with a positioning statement.',
  },
  {
    id: 'marketing_mix_4ps_7ps',
    name: '4Ps / 7Ps Marketing Mix',
    domain: 'marketing',
    definition: 'Coordinate Product, Price, Place, and Promotion, plus People, Process, and Physical Evidence where relevant.',
    whenToUse: 'Tactical marketing planning.',
    expectedOutput: 'A coherent marketing mix.',
  },
  {
    id: 'jobs_to_be_done',
    name: 'Jobs-to-be-Done',
    domain: 'marketing',
    definition: 'Describe the progress customers seek when they hire a product or service.',
    whenToUse: 'Innovation or positioning.',
    expectedOutput: 'Job statements with solution criteria.',
  },
  {
    id: 'clv_cac',
    name: 'CLV + CAC',
    domain: 'marketing',
    definition: 'Compare customer lifetime value with customer acquisition cost.',
    whenToUse: 'Growth economics or retention investment.',
    expectedOutput: 'A CLV:CAC ratio with payback period.',
  },
  {
    id: 'aarrr_pirate_metrics',
    name: 'AARRR (Pirate Metrics)',
    domain: 'marketing',
    definition: 'Measure Acquisition, Activation, Retention, Revenue, and Referral.',
    whenToUse: 'Digital or growth optimization.',
    expectedOutput: 'Funnel diagnostics.',
  },
  {
    id: 'customer_journey_mapping',
    name: 'Customer Journey Mapping',
    domain: 'marketing',
    definition: 'Visualize the end-to-end customer experience across interactions and stages.',
    whenToUse: 'Experience design.',
    expectedOutput: 'A journey map with prioritized friction points.',
  },
  {
    id: 'okrs',
    name: 'OKRs',
    domain: 'organization',
    definition: 'Set qualitative Objectives supported by measurable Key Results.',
    whenToUse: 'Goal setting or execution cadence.',
    expectedOutput: 'A cascaded OKR set with tracking.',
  },
  {
    id: 'raci_matrix',
    name: 'RACI Matrix',
    domain: 'organization',
    definition: 'Clarify decision and delivery roles as Responsible, Accountable, Consulted, and Informed.',
    whenToUse: 'Project governance or decision-rights clarity.',
    expectedOutput: 'A RACI chart.',
  },
  {
    id: 'scenario_planning_decision_trees_expected_value',
    name: 'Scenario Planning & Decision Trees / Expected Value',
    domain: 'organization',
    definition: 'Structure alternative futures and compare decision paths using probabilities, outcomes, and expected value.',
    whenToUse: 'High-uncertainty decisions.',
    expectedOutput: 'A preferred option across scenarios with expected value.',
  },
  {
    id: 'pyramid_principle',
    name: 'Pyramid Principle',
    domain: 'organization',
    definition: 'Lead with the governing thought, followed by MECE-grouped supporting arguments.',
    whenToUse: 'All executive communication.',
    expectedOutput: 'A clear top-down recommendation structure.',
  },
  {
    id: 'bezos_type_1_type_2_decisions',
    name: 'Bezos Type 1 / Type 2 Decisions',
    domain: 'organization',
    definition: 'Classify irreversible, high-cost decisions as Type 1 and reversible, low-cost decisions as Type 2.',
    whenToUse: 'Any decision requiring an escalate-or-act determination.',
    expectedOutput: 'A decision classification with recommended decision speed.',
  },
]);

function getAllFrameworks() {
  return frameworks;
}

function getFrameworksByDomain(domain) {
  return frameworks.filter(framework => framework.domain === String(domain || '').trim().toLowerCase());
}

function getFrameworkById(id) {
  return frameworks.find(framework => framework.id === String(id || '').trim().toLowerCase()) || null;
}

module.exports = {
  DOMAINS,
  frameworks,
  getAllFrameworks,
  getFrameworksByDomain,
  getFrameworkById,
};
